#ifndef AURORA_CPU_LOCAL_OFFSETS_H
#define AURORA_CPU_LOCAL_OFFSETS_H

#define AURORA_CPU_LOCAL_SELF_OFFSET             0
#define AURORA_CPU_LOCAL_LOGICAL_ID_OFFSET       8
#define AURORA_CPU_LOCAL_CURRENT_SPACE_OFFSET   16
#define AURORA_CPU_LOCAL_SYSCALL_RSP_OFFSET     24
#define AURORA_CPU_LOCAL_USER_RSP_OFFSET        32

#endif
